name: sanigado
description: "Projeto Sanidade do Gado"

publish_to: 'none' # Remove esta linha se quiser publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  http: ^1.3.0
  path_provider: ^2.1.1
  image_picker: ^1.0.7
  intl: ^0.20.2
  universal_io: ^2.0.4
  connectivity_plus: ^6.1.4
  flutter_image_compress: ^2.1.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4 # Adicionando flutter_launcher_icons

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icons/icon.png
    - lib/assets/images/marcadagua.png

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icons/icon.png"
  adaptive_icon_background: "#FFFFFF" # Cor de fundo (Android 12+)
